default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  username: root
  password: rootpassword
  host: localhost
  port: 3307

development:
  <<: *default
  database: chat_system_development

test:
  <<: *default
  database: chat_system_test

production:
  <<: *default
  database: chat_system_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
