FactoryBot.define do
  factory :application do
    name { Faker::App.name }
    
    # Token is auto-generated by model, but we can override for tests
    trait :with_token do
      token { SecureRandom.hex(10) }
    end
    
    trait :with_chats do
      after(:create) do |application|
        create_list(:chat, 3, application: application)
      end
    end
  end
end
