source "https://rubygems.org"

ruby "3.4.7"

# Core Rails
gem "rails", "~> 7.1.5"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"

# Redis for caching, counters, and Sidekiq
gem "redis", "~> 5.0"

# Background Jobs
gem "sidekiq", "~> 7.0"

# Elasticsearch for full-text search
gem "elasticsearch-model", "~> 7.2"
gem "elasticsearch-rails", "~> 7.2"

# Security
gem "rack-attack", "~> 6.7"
gem "rack-cors", "~> 2.0"

# Pagination
gem "kaminari"

# API Documentation (Swagger)
gem "rswag-api"
gem "rswag-ui"

# Boot time optimization
gem "bootsnap", require: false

# Timezone data for Windows
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.2"
  gem "rswag-specs"
  gem "dotenv-rails"
end

group :development do
  gem "spring"
end

group :test do
  gem "database_cleaner-active_record", "~> 2.1"
  gem "shoulda-matchers", "~> 6.0"
  gem "simplecov", require: false
end
